# Generated by Django 3.1.4 on 2021-01-17 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201228_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('help_type', models.CharField(choices=[('', 'Choose a type...'), ('0', 'Report an issue'), ('1', 'Report a post'), ('2', 'Feedback'), ('3', 'Support'), ('4', 'Other')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
