# Generated by Django 3.1.4 on 2021-01-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, default='No info was provided', null=True),
        ),
    ]
